configurations:
  - id: backend
    name: Backend # Displayed in Qodana Cloud UI
    description: Configurations used for backend projects # Displayed in Qodana Cloud UI
    qodanaYaml: backend/qodana.yaml # path to the config file

  - id: frontend
    name: Frontend
    description: Configurations used for frontend projects
    qodanaYaml: frontend/qodana.yaml
        